#!/usr/bin/python

import cgi
import sqlite3
import urlparse
import os

#Change this
PATH_TO_INSTALL = "/home/zhuowei/Documents/repos/URLShortener"

form = cgi.FieldStorage()

urlToAdd = form.getfirst("url")

if urlToAdd == None:
	print "Content-Type: text/plain"
	print
	print "Please enter a url."
	exit()

parsed_url = urlparse.urlparse(urlToAdd)

if parsed_url.scheme == '' or parsed_url.netloc == '':
	print "Content-Type: text/plain"
	print
	print "That wasn't a url, you silly goose!"
	exit()

conn = sqlite3.connect(PATH_TO_INSTALL + "/c/data/urls.db")

c = conn.cursor();

c.execute("insert into urls (url) values (?)", (parsed_url.geturl(),))
c.execute("select last_insert_rowid()")
result = c.fetchone()
conn.commit()
conn.close()

print "Content-Type: text/plain"
print
print "Done. your url is at:"
print os.environ["SERVER_NAME"] + "/c/g?" + str(result[0])


